<a href="https://colab.research.google.com/github/wajeehulhassan0051/Deep-learning-lab/blob/main/EXP%233exceloss_multiclass_classification_180325.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Ground truth labels (one-hot encoded)
y_true = np.array([
    [1, 0, 0, 0, 0],  # Sample 1: Class 1
    [0, 1, 0, 0, 0],  # Sample 2: Class 2
    [0, 0, 1, 0, 0],   # Sample 3: Class 3
    [0, 0, 0, 1, 0],   # Sample 4: Class 4
     [0, 0, 0, 0, 1],   # Sample 5: Class 5
])

# Model predictions (logits)
logits = np.array([
       [2.0, 1.0, 0.1, 0.1, 0.6],  # Sample 1
    [0.5, 2.5, 0.2, 0.2, 0.7],  # Sample 2
    [0.1, 0.2, 3.0, 0.8, 0.7],   # Sample 3
     [0.1, 0.9, 3.0, 0.8, 0.7],   # Sample 4
     [0.1, 0.7, 3.0, 0.8, 0.7],   # Sample 5

])

# Softmax function
def softmax(x):
    exp_x = np.exp(x - np.max(x, axis=-1, keepdims=True))  # Numerical stability
    return exp_x / np.sum(exp_x, axis=-1, keepdims=True)

# Compute softmax probabilities
probs = softmax(logits)
print("Softmax Probabilities:\n", probs)

# Compute log(probs)
log_probs = np.log(probs)
print("\nLog of Softmax Probabilities:\n", log_probs)

# Compute y_true * log(probs)
y_true_log_probs = y_true * log_probs
print("\ny_true * log(probs):\n", y_true_log_probs)

# Compute CE loss for each sample
ce_loss = -np.sum(y_true_log_probs, axis=-1)
print("\nCE Loss per Sample:", ce_loss)

# Average CE loss for the dataset
avg_ce_loss = np.mean(ce_loss)
print("\nAverage CE Loss for the Dataset:", avg_ce_loss)

Softmax Probabilities:
 [[0.52257153 0.19224332 0.0781603  0.0781603  0.12886455]
 [0.09015429 0.66615512 0.06678794 0.06678794 0.1101147 ]
 [0.04146764 0.04582883 0.75363897 0.08350558 0.07555897]
 [0.03962663 0.08819068 0.72018005 0.07979822 0.07220442]
 [0.0402704  0.07337745 0.73188008 0.08109462 0.07337745]]

Log of Softmax Probabilities:
 [[-0.64899341 -1.64899341 -2.54899341 -2.54899341 -2.04899341]
 [-2.40623272 -0.40623272 -2.70623272 -2.70623272 -2.20623272]
 [-3.18284184 -3.08284184 -0.28284184 -2.48284184 -2.58284184]
 [-3.22825402 -2.42825402 -0.32825402 -2.52825402 -2.62825402]
 [-3.21213861 -2.61213861 -0.31213861 -2.51213861 -2.61213861]]

y_true * log(probs):
 [[-0.64899341 -0.         -0.         -0.         -0.        ]
 [-0.         -0.40623272 -0.         -0.         -0.        ]
 [-0.         -0.         -0.28284184 -0.         -0.        ]
 [-0.         -0.         -0.         -2.52825402 -0.        ]
 [-0.         -0.         -0.         -0.         -2.61213861]